name: Reaction_Dynamics
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2018.8.24=py35_1
  - cycler=0.10.0=py35hb89929e_0
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.4=233
  - kiwisolver=1.0.1=py35h219a9d8_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h0a44026_6
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - matplotlib=3.0.0=py35h54f8f79_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py35hb8a8100_0
  - mkl_random=1.0.1=py35h5d10147_1
  - ncurses=6.2=h0a44026_1
  - numpy=1.15.2=py35h6a91979_0
  - numpy-base=1.15.2=py35h8a80b8c_0
  - openssl=1.0.2u=h1de35cc_0
  - pip=10.0.1=py35_0
  - pyparsing=2.4.7=py_0
  - python=3.5.6=hc167b69_0
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - readline=7.0=h1de35cc_5
  - scipy=1.1.0=py35h28f7352_1
  - setuptools=40.2.0=py35_0
  - six=1.11.0=py35_1
  - sqlite=3.31.1=h5c1f38d_1
  - tbb=2020.0=h04f5b5a_0
  - tbb4py=2018.0.5=py35h04f5b5a_0
  - tk=8.6.8=ha441bb4_0
  - tornado=5.1.1=py35h1de35cc_0
  - wheel=0.31.1=py35_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
prefix: /usr/local/anaconda3/envs/Reaction_Dynamics

